[package]
name = "tfhe_cmp"
version = "0.1.0"
edition = "2024"

[dependencies]
tfhe = { version = "1.0.1", features = ["integer"] }
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.2"
base64 = "0.21"